from __future__ import annotations

from pathlib import Path


THESIS = Path("thesis")

OUTPUT_PATH = (
    THESIS
    / "chapter_4_robustness_implementation_draft.md"
)

EMPIRICAL_PACK = (
    THESIS
    / "empirical_update_pack.md"
)


ROBUSTNESS_TEXT = r"""# Chapter 4 — Robustness and Implementation Draft

## 1. Introduction

This chapter evaluates whether the empirical results remain economically meaningful under alternative implementation and calibration assumptions.

The purpose of robustness analysis is not to identify the parameter combination with the highest historical Sharpe ratio. It is to determine whether the principal conclusions survive when assumptions governing transaction costs, risk estimation, exposure limits, sample selection and investor risk aversion are changed.

The chapter preserves the distinction between the two empirical evidence layers.

The equity–bond allocation layer is primarily exposed to:

- dynamic-weight turnover;
- model instability;
- excessive reactions to estimated regime probabilities;
- implementation costs generated by frequent rebalancing.

The direct-variance layer is exposed to:

- monthly contract renewal;
- negatively skewed payoff shocks;
- errors in lagged volatility forecasts;
- choice of notional cap;
- choice of entry filter;
- transaction-cost assumptions;
- sensitivity to crisis periods and sample composition.

The two layers therefore require different robustness tests.

The main conclusion is that the allocation models remain economically competitive in selected dimensions but do not establish robust benchmark dominance. The United States HMM can be made more implementable through partial rebalancing, but its principal advantage remains drawdown control rather than superior welfare.

The direct-variance results are more asymmetric. The selected United States strategy remains sensitive to risk-estimation choices and does not consistently dominate conventional benchmarks in certainty-equivalent terms. The selected European strategy remains strong across the principal robustness dimensions tested.

---

## 2. Principles of the robustness design

Five principles govern the analysis.

First, all sensitivity calculations use only information that would have been available before the corresponding strategy return.

Second, comparisons within a calibration dimension are aligned to a common sample. A strategy using a 12-month volatility window and a strategy using a 60-month window are therefore compared over the dates available to both specifications.

Third, transaction costs are applied to the economically relevant implementation quantity.

For equity–bond allocation, the cost base is the change in portfolio weights.

For direct variance carry, the cost base is the absolute notional of the newly initiated monthly exposure because the previous one-month exposure has settled.

Fourth, robustness is evaluated through multiple dimensions rather than a single Sharpe ratio. The analysis considers:

- annualized return;
- realized volatility;
- Sharpe ratio;
- maximum drawdown;
- CVaR;
- turnover;
- mean–variance certainty equivalent;
- CRRA certainty equivalent;
- welfare differences relative to 60/40 and 1/N.

Fifth, the robustness results do not eliminate the methodological limitations of the direct-variance approximation. Stability within a stylized model does not transform that model into an observed variance-swap backtest.

---

## 3. Allocation-model implementation robustness

### 3.1 Baseline implementation burden

The strongest allocation models generally require substantially more trading than the simple benchmarks.

The principal aligned results are:

| Market | Strategy | Sharpe | Max Drawdown | Avg Turnover |
|---|---|---:|---:|---:|
| US | 60/40 | 1.024 | −20.06% | 1.47% |
| US | 1/N Equity–Bond | 1.025 | −19.10% | 1.53% |
| US | HMM RV + Log VRP | 1.019 | −16.67% | 25.35% |
| US | RSM RV + Raw VRP | 0.949 | −15.43% | 36.69% |
| EU | 60/40 | 0.292 | −20.32% | 1.74% |
| EU | 1/N Equity–Bond | 0.280 | −19.66% | 1.81% |
| EU | HMM RV | 0.218 | −19.39% | 17.76% |
| EU | RSM RV + Raw VRP | 0.281 | −20.47% | 34.00% |
| EU | ML Random Forest + VRP | 0.274 | −19.17% | 15.38% |

The contrast is substantial.

Simple balanced portfolios change weights only as asset prices drift away from their fixed targets. Their turnover remains below 2% in the aligned samples.

Dynamic models modify exposure as estimated stress probabilities change. Their average turnover ranges from approximately 15% to more than 36%.

This does not make dynamic allocation invalid, but it raises the standard required for economic justification. A modest drawdown improvement must be evaluated against greater trading, model risk and operational complexity.

---

### 3.2 United States allocation cost sensitivity

The United States HMM RV + Log VRP specification provides the clearest allocation example because it combines a competitive Sharpe ratio with improved drawdown.

Its cost sensitivity is:

| Strategy | 0 bps | 10 bps | 25 bps | 50 bps |
|---|---:|---:|---:|---:|
| 60/40 Sharpe | 1.026 | 1.024 | 1.021 | 1.016 |
| 1/N Sharpe | 1.028 | 1.025 | 1.022 | 1.016 |
| HMM RV + Log VRP Sharpe | 1.055 | 1.019 | 0.963 | 0.869 |

Before transaction costs, the HMM has a higher Sharpe ratio than the balanced benchmarks.

At the baseline cost of 10 basis points per unit of weight turnover, its Sharpe ratio falls to 1.019 and becomes slightly lower than both balanced benchmarks.

At 25 and 50 basis points, the performance difference becomes more material.

The benchmark portfolios are much less sensitive because their turnover is low.

The allocation result therefore depends partly on execution assumptions. The HMM does not generate a sufficiently large gross advantage to absorb high transaction costs without losing its competitive position.

Its drawdown advantage is more persistent. At the baseline cost, its maximum drawdown is −16.67%, compared with −20.06% for 60/40 and −19.10% for 1/N.

This supports a defensive interpretation of the HMM rather than a claim of broad performance dominance.

---

### 3.3 No-trade bands

A no-trade band avoids rebalancing when the difference between the current and desired weights is small.

For the United States HMM RV + Log VRP model, increasing the band from zero to 10% changes:

- the Sharpe ratio from approximately 1.019 to 1.026;
- average turnover from approximately 25.30% to 23.53%.

The effect is favorable but limited.

The no-trade band eliminates small adjustments but does not prevent large changes when the estimated state probability moves substantially. It therefore cannot fully resolve the turnover generated by regime switching.

---

### 3.4 Partial rebalancing

Partial rebalancing moves the portfolio gradually toward the target allocation:

\[
w_t^{implemented}
=
\lambda w_t^{target}
+
(1-\lambda)
w_{t-1}^{implemented}
\]

where \(\lambda\) is the adjustment speed.

A value of one corresponds to full rebalancing. Lower values smooth the transition between portfolio states.

For HMM RV + Log VRP:

| Implementation | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | Avg Turnover |
|---|---:|---:|---:|---:|---:|
| Full rebalancing | 8.36% | 8.24% | 1.019 | −16.67% | 25.35% |
| Partial rebalancing, \(\lambda=0.25\) | 8.69% | 8.62% | 1.014 | −18.04% | 9.10% |

Partial rebalancing reduces turnover by approximately two thirds.

The Sharpe ratio declines only marginally, while the maximum drawdown remains below that of 60/40 and Buy-and-Hold Equity.

This makes the 0.25 implementation more defensible than full monthly movement to the estimated target.

However, the result does not imply benchmark dominance. The strategy still has more turnover than 60/40 and 1/N, and its Sharpe ratio remains slightly lower.

The correct interpretation is:

> Partial rebalancing improves the implementability of the selected United States HMM without converting it into a statistically superior allocation strategy.

---

### 3.5 European allocation robustness

The corrected European results do not identify an allocation model whose baseline performance would justify a detailed search for implementation parameters.

The strongest HMM has a Sharpe ratio of 0.218. The strongest RSM reaches 0.281 and the strongest ML strategy reaches 0.274.

These values remain close to or below the simple benchmarks, while the dynamic strategies require materially greater turnover.

The inclusion of raw or log VRP can improve selected model specifications, but the improvement is not stable across model families.

The European allocation conclusion is therefore robust in a negative but precise sense:

- VRP-related variables contain information;
- model performance varies with feature transformation;
- some dynamic portfolios improve particular downside measures;
- no tested allocation framework establishes robust economic dominance over simple benchmarks.

---

## 4. Direct-variance implementation framework

### 4.1 Baseline implementation assumptions

The baseline direct-variance strategy uses:

- one-month variance-payoff observations;
- lagged implied variance as the strike proxy;
- subsequent trailing realized variance as the settlement proxy;
- a 36-month payoff-volatility window;
- a minimum of 24 risk observations;
- a 25% maximum absolute notional;
- 10 basis points of cost per unit of monthly notional entered.

The risk target is an ex ante sizing objective. It is not an ex post volatility guarantee.

This distinction is particularly important in the United States, where the always-active 10% strategy realizes volatility above 16%.

A negatively skewed payoff can experience a shock far outside the distribution implied by its lagged volatility estimate.

---

### 4.2 Monthly roll-cost treatment

The direct-variance exposure settles every month.

Even when the desired notional remains unchanged, a new exposure must be initiated.

The transaction-cost base is therefore:

\[
Turnover^{cost}_t
=
|N_t|
\]

rather than:

\[
|N_t-N_{t-1}|
\]

Net return is:

\[
R^{net}_t
=
N_t
\widetilde{\Pi}^{short}_t
-
c|N_t|
\]

The change in desired notional is retained as an additional diagnostic but is not used as the cost base.

The baseline average cost notionals are:

- approximately 2.01% for the selected United States High-VRP strategy;
- approximately 4.39% for the selected European positive-VRP strategy.

---

## 5. Transaction-cost sensitivity

The tested direct-variance costs are:

\[
0,\ 10,\ 25,\ 50
\text{ basis points}
\]

### 5.1 United States

| Cost | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | CVaR 95 | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| 0 bps | 6.26% | 7.18% | 0.885 | −23.42% | −5.26% | 5.06% | −0.69% | −0.43% |
| 10 bps | 6.23% | 7.17% | 0.882 | −23.46% | −5.26% | 5.04% | −0.71% | −0.45% |
| 25 bps | 6.19% | 7.17% | 0.877 | −23.53% | −5.27% | 5.00% | −0.74% | −0.48% |
| 50 bps | 6.13% | 7.16% | 0.869 | −23.63% | −5.28% | 4.95% | −0.80% | −0.54% |

The United States High-VRP strategy is not highly sensitive to the tested cost range because its average active notional is low.

However, the strategy begins with a negative certainty-equivalent difference against both benchmarks. Higher costs therefore reinforce, rather than create, its welfare disadvantage.

### 5.2 Europe

| Cost | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | CVaR 95 | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| 0 bps | 13.14% | 9.70% | 1.329 | −21.35% | −7.34% | 10.54% | 9.32% | 9.04% |
| 10 bps | 13.08% | 9.70% | 1.324 | −21.36% | −7.34% | 10.49% | 9.27% | 8.99% |
| 25 bps | 12.99% | 9.69% | 1.316 | −21.38% | −7.35% | 10.41% | 9.19% | 8.91% |
| 50 bps | 12.84% | 9.69% | 1.303 | −21.42% | −7.37% | 10.28% | 9.06% | 8.78% |

The European result remains strong throughout the tested range.

At 50 basis points per unit of monthly notional, the Sharpe ratio remains above 1.30 and the mean–variance certainty-equivalent advantage remains close to nine percentage points.

This test does not prove that actual derivative costs would be lower than the break-even level. It shows that the result is not generated by the difference between zero and moderate stylized roll costs.

---

## 6. Volatility-estimation window

The payoff-volatility windows tested are:

\[
12,\ 24,\ 36,\ 60
\text{ months}
\]

All specifications in this sensitivity test are aligned to the common sample required by the 60-month window. Consequently, the 36-month figures in this section differ slightly from the unrestricted baseline.

### 6.1 United States

| Window | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | CVaR 95 | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| 12 months | 8.10% | 16.15% | 0.578 | −50.69% | −11.71% | 2.81% | −3.30% | −2.94% |
| 24 months | 6.38% | 9.94% | 0.678 | −32.59% | −7.18% | 4.27% | −1.85% | −1.49% |
| 36 months | 6.50% | 7.10% | 0.926 | −23.46% | −5.18% | 5.32% | −0.80% | −0.44% |
| 60 months | 6.26% | 6.87% | 0.922 | −23.00% | −5.17% | 5.15% | −0.97% | −0.60% |

The 12-month estimate is unstable. It assigns excessive notional before large payoff shocks and generates a drawdown above 50%.

Windows of 36 and 60 months produce much more stable results.

This supports the use of a relatively long risk-estimation window for the United States payoff.

It also confirms that the risk target should not be interpreted as a realized-volatility guarantee.

### 6.2 Europe

| Window | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | CVaR 95 | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| 12 months | 18.35% | 11.21% | 1.570 | −15.92% | −7.92% | 14.45% | 11.74% | 11.78% |
| 24 months | 15.66% | 10.46% | 1.453 | −19.97% | −8.06% | 12.46% | 9.75% | 9.79% |
| 36 months | 14.15% | 9.79% | 1.409 | −21.36% | −7.58% | 11.40% | 8.69% | 8.73% |
| 60 months | 13.92% | 8.93% | 1.513 | −17.21% | −6.70% | 11.52% | 8.80% | 8.84% |

Every tested European window produces a Sharpe ratio above 1.40 on the common sample.

The result is therefore not dependent on a unique 36-month calibration.

The strongest return is obtained with the shortest window, but the 60-month window produces lower realized volatility and a smaller drawdown.

The objective is not to select the ex post best window. The central finding is that the economic conclusion remains stable across the full range.

---

## 7. Notional-cap sensitivity

The tested maximum absolute notionals are:

\[
5\%,\ 10\%,\ 15\%,\ 25\%,\ 50\%
\]

### 7.1 United States

| Cap | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|
| 5% | 5.37% | 6.53% | 0.836 | −23.46% | 4.39% | −1.35% | −1.09% |
| 10% | 6.25% | 7.17% | 0.884 | −23.46% | 5.05% | −0.70% | −0.44% |
| 15% | 6.23% | 7.17% | 0.882 | −23.46% | 5.04% | −0.71% | −0.45% |
| 25% | 6.23% | 7.17% | 0.882 | −23.46% | 5.04% | −0.71% | −0.45% |
| 50% | 6.23% | 7.17% | 0.882 | −23.46% | 5.04% | −0.71% | −0.45% |

The High-VRP strategy rarely requires notionals above 10%.

Caps above 15% are therefore non-binding.

Reducing the cap to 5% lowers return and volatility but does not remove the historical maximum drawdown, because the principal drawdown occurs during periods in which the strategy already uses a relatively low notional.

### 7.2 Europe

| Cap | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|
| 5% | 12.07% | 7.94% | 1.482 | −17.95% | 10.19% | 8.97% | 8.69% |
| 10% | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |
| 15% | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |
| 25% | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |
| 50% | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |

The European result survives a substantial tightening of the exposure constraint.

With a 5% cap, the strategy produces:

- annualized return of 12.07%;
- volatility of 7.94%;
- Sharpe ratio of 1.482;
- maximum drawdown of −17.95%;
- CEQ advantages above eight percentage points relative to both benchmarks.

The result is therefore not driven by occasional use of the baseline 25% maximum notional.

Caps above 10% are non-binding in the baseline sample.

---

## 8. Subperiod stability

### 8.1 United States

| Period | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|
| Full sample | 6.23% | 7.17% | 0.882 | −23.46% | 5.04% | −0.71% | −0.45% |
| First half | 6.64% | 5.84% | 1.131 | −6.11% | 5.76% | 1.68% | 1.43% |
| Second half | 5.83% | 8.32% | 0.726 | −23.46% | 4.31% | −3.11% | −2.33% |
| Pre-Covid | 5.40% | 7.19% | 0.770 | −13.60% | 4.24% | −1.13% | −1.15% |
| Covid and after | 7.87% | 7.17% | 1.096 | −15.37% | 6.58% | 0.13% | 0.92% |

The United States result is not uniform through time.

The first half produces a Sharpe ratio above one and positive CEQ differences.

The second half produces greater volatility, a lower Sharpe ratio and negative welfare differences.

The strategy also performs better after Covid than in the preceding period.

This instability prevents a strong claim of persistent benchmark dominance.

### 8.2 Europe

| Period | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|
| Full sample | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |
| First half | 12.77% | 7.07% | 1.743 | −6.33% | 11.08% | 11.09% | 10.16% |
| Second half | 13.38% | 11.79% | 1.132 | −21.36% | 9.87% | 7.44% | 7.81% |
| Pre-Covid | 12.81% | 7.30% | 1.695 | −6.33% | 11.04% | 10.43% | 9.66% |
| Covid and after | 13.39% | 11.92% | 1.121 | −21.16% | 9.81% | 7.92% | 8.22% |

The European strategy remains profitable in every tested subperiod.

Risk increases in the second half and after Covid, but annualized return remains close to 13%.

The CEQ advantage remains above seven percentage points against both benchmarks in the weaker subperiods.

The full-sample European result is therefore not generated solely by an unusually favorable first half.

---

## 9. Crisis-exclusion analysis

The crisis tests remove the following windows individually and jointly:

- Global Financial Crisis;
- European sovereign-debt crisis;
- Volmageddon;
- Covid shock;
- inflation and interest-rate shock.

Removing crisis months serves two purposes.

First, it tests whether positive performance is generated by mechanically profiting from a small number of volatility events.

Second, it identifies whether tail losses during crises dominate the full-sample result.

### 9.1 United States

The United States High-VRP strategy remains sensitive to the identity of the excluded crisis.

Removing particular stress episodes can improve its Sharpe ratio and drawdown, but the welfare conclusion is not uniformly reversed.

This confirms that the strategy’s economic value is partly dependent on the timing of a small number of volatility shocks.

The crisis analysis therefore supports the cautious United States conclusion rather than a claim of structural dominance.

### 9.2 Europe

The European positive-VRP strategy remains strong when major crises are excluded jointly.

| Scenario | Retained Obs | Ann. Return | Ann. Vol | Sharpe | Max Drawdown | MV CEQ | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| Full sample | 170 | 13.08% | 9.70% | 1.324 | −21.36% | 10.49% | 9.27% | 8.99% |
| Exclude all major crises | 141 | 17.38% | 8.80% | 1.877 | −14.05% | 14.59% | 8.57% | 8.90% |

Excluding 29 crisis observations increases the Sharpe ratio and reduces maximum drawdown.

The CEQ advantage remains large relative to both benchmarks.

The European result is therefore not created by gains concentrated exclusively in the designated crisis windows.

This does not imply that crisis-period trading would be frictionless. It only shows that the historical statistical result survives their removal.

---

## 10. Risk-aversion stability

The tested risk-aversion coefficients are:

\[
\gamma
\in
\{1,3,5,10\}
\]

### 10.1 United States

| Gamma | MV CEQ | CRRA CE | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---:|---:|---:|---:|---:|
| 1 | 6.07% | 6.23% | −1.65% | −0.91% |
| 3 | 5.55% | 5.64% | −1.18% | −0.68% |
| 5 | 5.04% | 5.00% | −0.71% | −0.45% |
| 10 | 3.75% | 3.11% | 0.47% | 0.12% |

The United States High-VRP strategy is inferior to both benchmarks for risk-aversion coefficients from one to five.

It becomes slightly favorable under the mean–variance criterion at \(\gamma=10\), because its lower volatility receives greater weight.

This result is not sufficient to establish general superiority. It shows that the strategy may be attractive to a highly risk-averse investor who assigns substantial value to volatility reduction.

### 10.2 Europe

| Gamma | MV CEQ | CRRA CE | Delta CEQ vs 60/40 | Delta CEQ vs 1/N |
|---:|---:|---:|---:|---:|
| 1 | 12.37% | 13.08% | 8.81% | 9.10% |
| 3 | 11.43% | 11.93% | 9.04% | 9.05% |
| 5 | 10.49% | 10.67% | 9.27% | 8.99% |
| 10 | 8.14% | 6.96% | 9.83% | 8.84% |

The European CEQ advantage remains positive and economically large at every tested risk-aversion level.

The CRRA certainty equivalent declines more rapidly at high risk aversion because it is more sensitive to the negatively skewed payoff distribution.

Nevertheless, the central welfare conclusion remains unchanged.

---

## 11. Interpretation of the robustness evidence

The robustness results produce four principal conclusions.

First, the United States allocation model can be made more implementable through partial rebalancing. The reduction in turnover is substantial, but the model remains economically close to the simple benchmarks rather than clearly superior.

Second, the selected United States direct-variance strategy is robust to moderate transaction costs and long volatility-estimation windows, but its results vary materially across subperiods. It does not establish consistent welfare dominance.

Third, the European positive-VRP direct-variance strategy survives every principal calibration test:

- costs up to 50 basis points;
- volatility windows from 12 to 60 months;
- a 5% notional cap;
- first-half and second-half samples;
- pre-Covid and post-Covid periods;
- major-crisis exclusions;
- risk-aversion coefficients from one to ten.

Fourth, robustness inside the model does not eliminate execution uncertainty. The European result is statistically and economically strong under the tested assumptions, but the magnitude may be overstated by the absence of exact derivative-market frictions.

---

## 12. Implementation limitations

Several implementation elements remain outside the model.

### 12.1 Exact variance strike

The volatility-index square is not an exact forward variance-swap strike.

A full implementation would require the complete option surface and the relevant static replication formula.

### 12.2 Settlement convention

The realized-variance settlement proxy is a trailing 21-observation annualized estimate.

It is not the exact sum of squared returns over a contractual calendar interval.

### 12.3 Financing and collateral

The model does not include:

- collateral remuneration;
- funding spreads;
- initial margin;
- variation margin;
- liquidity reserves required during losses.

### 12.4 Daily mark-to-market

Only monthly payoff observations are represented.

Intramonth losses may create margin or liquidity constraints even when the final monthly payoff is positive.

### 12.5 Bid–ask spread and dealer costs

The cost grid is stylized.

Actual variance-swap or option-replication costs may vary with:

- maturity;
- market volatility;
- dealer balance-sheet conditions;
- trade size;
- crisis liquidity;
- counterparty quality.

### 12.6 Market impact and capacity

The strategy is evaluated without market impact.

A payoff accessible to a small investor may not scale to institutional size without changing execution costs.

### 12.7 Model and data risk

The European result depends on reconstructed VSTOXX history and a model-based payoff mapping.

Although date parsing and gap handling have been audited, residual source and methodology differences remain possible.

---

## 13. Robustness conclusion

The robustness evidence strengthens the main thesis result while also narrowing its interpretation.

The allocation models do not provide a universal improvement over simple portfolios. Their value is concentrated in selected risk dimensions and depends on turnover control.

The United States direct-variance result remains economically plausible but not dominant. Its performance is weaker in the second half of the sample and its welfare advantage is generally negative or statistically uncertain.

The European direct-variance result is considerably more stable. It survives changes in costs, risk estimation, exposure constraints, subperiods, crisis treatment and investor risk aversion.

The appropriate conclusion is therefore:

> The European direct-variance result is robust within the model-based framework, but it remains evidence about a stylized variance-payoff mechanism rather than proof of an exactly replicable traded return.

The final chapter evaluates how this evidence should be interpreted in light of the remaining data, modelling, statistical and implementation limitations.
"""


def validate_source() -> None:
    if not EMPIRICAL_PACK.exists():
        raise FileNotFoundError(
            EMPIRICAL_PACK
        )

    source = EMPIRICAL_PACK.read_text(
        encoding="utf-8"
    )

    required = [
        "Transaction-cost sensitivity",
        "Volatility-lookback sensitivity",
        "Notional-cap sensitivity",
        "Subperiod stability",
        "Risk-aversion stability",
    ]

    for marker in required:
        if marker not in source:
            raise AssertionError(
                f"Empirical pack missing: "
                f"{marker}"
            )


def validate_text(
    text: str,
) -> None:
    required = [
        "Partial rebalancing",
        "25.35%",
        "9.10%",
        "50 basis points",
        "12 to 60 months",
        "5% notional cap",
        "Exclude all major crises",
        "141",
        "1.877",
        "risk-aversion coefficients",
        "monthly contract renewal",
        (
            "robust within the "
            "model-based framework"
        ),
    ]

    stale = [
        "collapses in Europe",
        "collapses in the European",
        "-2.8511",
        "-0.3625",
        "-0.9901",
        "0.1281",
        "127 observations",
        (
            "more useful as a "
            "regime-state variable"
        ),
    ]

    for marker in required:
        if marker.lower() not in text.lower():
            raise AssertionError(
                f"Missing robustness marker: "
                f"{marker}"
            )

    for phrase in stale:
        if phrase.lower() in text.lower():
            raise AssertionError(
                f"Stale robustness phrase: "
                f"{phrase}"
            )

    if len(text.split()) < 3_000:
        raise AssertionError(
            "Robustness chapter "
            "unexpectedly short."
        )


def main() -> None:
    validate_source()
    validate_text(ROBUSTNESS_TEXT)

    OUTPUT_PATH.write_text(
        ROBUSTNESS_TEXT.strip() + "\n",
        encoding="utf-8",
    )

    print("=" * 100)
    print(
        "THESIS REWRITE STAGE 4 COMPLETE"
    )
    print("=" * 100)

    print(f"Updated: {OUTPUT_PATH}")

    print(
        f"Words: {len(ROBUSTNESS_TEXT.split())}"
    )

    print(
        f"Lines: "
        f"{len(ROBUSTNESS_TEXT.splitlines())}"
    )


if __name__ == "__main__":
    main()
